development:
  adapter: mysql
  encoding: utf8
  host: 192.168.1.10
  database: kiris2_development
  pool: 5
  username: kiris2
  password: abc123
test:
  adapter: mysql
  encoding: utf8
  host: 192.168.1.10
  database: kiris2_test
  pool: 5
  username: kiris2
  password: abc123
production:
  adapter: mysql
  encoding: utf8
  host: localhost
  database: kiris2_production
  pool: 5
  username: kiris2
  password: abc123
